#name: "Copilot Setup Steps"

# Configure Copilotâ€™s environment with GitHub Actions - You can use Actions to install custom tools that Coding agent will need to preform tasks with specfic requirements. 
# Automatically run the setup steps when they are changed
# Allows for streamlined validation,
# and allow manual testing through the repository's "Actions" tab

#on:
#  workflow_dispatch:
#  push:
#    paths:
#      - .github/workflows/copilot-setup-steps.yml
#  pull_request:
#    paths:
#      - .github/workflows/copilot-setup-steps.yml

#jobs:
  # The job MUST be called `copilot-setup-steps`
  # otherwise it will not be picked up by Copilot.
#  copilot-setup-steps:
##    runs-on: ubuntu-latest

    # Permissions set just for the setup steps
    # Copilot has permissions to its branch
    
#    permissions:
      # To allow us to clone the repo for setup
     # contents: read

    # The setup steps - install Python and our dependencies
   # steps:
   #   - name: Checkout code
   #     uses: actions/checkout@v4

   #   - name: Set up Python
   #     uses: actions/setup-python@v4
   #     with:
   #       python-version: "3.13"
   #       cache: "pip"

   #   - name: Install Python dependencies
   #     run: pip install -r requirements.txt

   #   - name: Install SQLite
  #      run: sudo apt update && sudo apt install sqlite3